name: "Deploy CodigoFacilito"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del código en master"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar versión"
